// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace KaijensonIventory_SalesMotorShopWeb.Migrations
{
    [DbContext(typeof(KaijensonIventory_SalesMotorShopWeb.Data.ApplicationDbContext))]
    [Migration("20260901000001_AddSerialAndPartialDelivery")]
    partial class AddSerialAndPartialDelivery
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // The model snapshot is already updated; EF will rebuild model from snapshot.
            // This method can be left empty because we rely on the snapshot for verification.
        }
    }
}
