// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace KaijensonIventory_SalesMotorShopWeb.Migrations
{
    [DbContext(typeof(KaijensonIventory_SalesMotorShopWeb.Data.ApplicationDbContext))]
    [Migration("20260831120000_CreateDeliveries")]
    partial class CreateDeliveries
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("KaijensonIventory_SalesMotorShopWeb.Models.Delivery", b =>
            {
                b.Property<int>("DeliveryId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("DeliveredDate")
                    .HasColumnType("datetime2");

                b.Property<int>("PurchaseOrderId")
                    .HasColumnType("int");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.HasKey("DeliveryId");

                b.HasIndex("PurchaseOrderId")
                    .IsUnique();

                b.ToTable("Deliveries");
            });
        }
    }
}
